version: '3.8'
services:
  # Serviço para o banco de dados PostgreSQL
  db:
    image: postgres:13
    container_name: api_ecommerce
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: api_ecommerce
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Volume para persistir os dados do PostgreSQL
volumes:
  postgres_data: